### ISSUE TITLE
Crash on particular country's tab

### ISSUE THREAD

**Issue by crazyuploader** [sidhuparas/Coronavirus-Tracker#5]
And for the log I got this

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.parassidhu.coronavirusapp.network.response.Delta.getConfirmed()' on a null object reference
	at com.parassidhu.coronavirusapp.ui.main.adapter.StandardListAdapter$StateViewHolder.bind(StandardListAdapter.kt:141)
	at com.parassidhu.coronavirusapp.ui.main.adapter.StandardListAdapter.onBindViewHolder(StandardListAdapter.kt:75)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2870)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2397)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1532)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7419)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
	at android.view.Choreographer.doFrame(Choreographer.java:819)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by sidhuparas** [comment]
The Covid19 API response was changed without versioning by the providers. This has been fixed already. Please pull the latest code from the repo.

**Comment by crazyuploader** [comment]
> 
> 
> The Covid19 API response was changed without versioning by the providers. This has been fixed already. Please pull the latest code from the repo.

What about the app? Isn't the app latest?

**Comment by sidhuparas** [comment]
Just updated the link. Thank you.
